# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Calibrate < Formula
  desc "Calibrate Public API: Programmatic API for CI/automation. Pass your key in the `X-API-Key` header."
  homepage "https://github.com/dalmia/calibrate-cli"
  version "0.0.54"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/dalmia/calibrate-cli/releases/download/v0.0.54/calibrate-cli_Darwin_x86_64.tar.gz"
      sha256 "dc718f58a169edbe7b418df4a844e6e29f8e756cb3c6d70b271139cc92ff7be3"

      define_method(:install) do
        bin.install "calibrate"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/dalmia/calibrate-cli/releases/download/v0.0.54/calibrate-cli_Darwin_arm64.tar.gz"
      sha256 "853e5218d90f8c1b32733e089fcf797106670a0e4433b8f139c4af2d15900d44"

      define_method(:install) do
        bin.install "calibrate"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/dalmia/calibrate-cli/releases/download/v0.0.54/calibrate-cli_Linux_x86_64.tar.gz"
      sha256 "798e6afadbfd38631459d04abe9104ab3e7502d98334fd2675b17e0d13038a09"
      define_method(:install) do
        bin.install "calibrate"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/dalmia/calibrate-cli/releases/download/v0.0.54/calibrate-cli_Linux_arm64.tar.gz"
      sha256 "1979d331018c15659864baebd6465b71d6531f7fcbdc391d3e7d9ce33206ee6f"
      define_method(:install) do
        bin.install "calibrate"
      end
    end
  end
end
